export const description =
  "I am a React frontend engineer with a passion for continuous learning and exploring new technologies. I enjoy applying this knowledge to create high-quality websites and mobile applications, always striving to provide a better user experience. The sense of accomplishment I feel upon completing a project is immense, and I constantly seek ways to refine and elevate my skills. I look forward to collaborating with teams that share a common goal, aiming to develop astonishing applications together. Thank you for reading.";

export const skills = [
  {
    title: "Frontend",
    icon: "Frontend",
    skills: [
      "React",
      "React Native",
      "Next.js",
      "TypeScript",
      "Styled Components",
      "Tailwind CSS",
      "Redux/Zustand",
      "Jest Unit Test",
      "React Query",
      "i18n / react-intl",
      "WebRTC/WebSocket",
      "Dexie.js",
      "Three.js",
    ],
  },
  {
    title: "Backend",
    icon: "Backend",
    skills: [
      "Node.js",
      "Express",
      "PHP",
      "RESTful API",
      "GCP Compute Engine",
      "JWT/Bcrypt",
      "Docker",
      "Github Action CI/CD",
      "Crawling",
      "Flask",
      "Line Bot",
    ],
  },
  {
    title: "DataBase & Tools",
    icon: "DatabaseOrTool",
    skills: [
      "Git",
      "MongoDB",
      "MySQL",
      "Firebase",
      "Postgresql",
      "LightHouse",
      "Vercel / Netlify / Github pages",
      "Figma",
      "Github",
      "Asana",
    ],
  },
];

export const SkillsInfo = [
  "Proficient in React and Next.js.",
  "Familiar with SCSS, StyledComponents, and Tailwind CSS.",
  "Experienced in integrating with RESTful APIs and using API testing tools, such as Postman.",
  "Capable of creating reusable React components and custom hooks.",
  "Well-versed in React Hooks and the use of Redux.",
  "Experience with frontend internationalization (i18n) techniques and tools.",
  "Familiar with implementing infinite scrolling functionality.",
  "Experience in integrating WebSocket for bidirectional binding.",
  "Created Chrome Extensions.",
  "Experience in writing projects with TypeScript.",
  "Worked with backend technologies like Node.js, Express, Flask, and PHP.",
  "Database operations and management: MySQL, MongoDB, Mongoose, and Firebase.",
  "Implemented authentication and encryption techniques, such as JWT and bcrypt.",
  "Experience in writing unit tests with Jest.",
  "Experience in using Dexie to access and operate on IndexedDB.",
  "Proficient in Git.",
  "Used free web hosting tools like Vercel, Netlify, and GitHub Pages.",
  "Docker containerization for efficient application deployment.",
  "CI/CD automation using GitHub Actions for continuous integration and delivery.",
  "Deployment on Google Cloud Platform (GCP) for scalability and stability.",
  "Self-hosting GCP Compute Engine instances for customized cloud infrastructure management.",
];
